### ISSUE TITLE
Problem with Configuration

### ISSUE THREAD

**Issue by jcamachott** [modxcms/flatso#3]
Hi, I installed Flatso a few days ago and everything seemed to be fine. Today however, I tried to edit the site config (Extras > Configuration) but even if I make no changes, when I click on Save Configuration, all I get is a small "Saving" box that stays on screen indefinitely. See below. Any ideas on this? I have cleared the cache within MODX and my next step is to manually clear all the cache files...but somehow I doubt thats it. 

MODX 2.4.3, tried in both Chrome and Firefox.

![image](https://cloud.githubusercontent.com/assets/1188776/13862093/63a2276a-ec67-11e5-8c3b-cd1eef7d95bd.png)

**Comment by jcamachott** [comment]
This is what is displayed in Chrome Dev Tools....BTW I posted this to the ClientConfig github page..so if you want you can close it here.

**Comment by dubrod** [comment]
Hey @jcamachott , thanks for using Flatso!  I see Mark already responded on his page. I'll leave this open incase anyone else finds this error with Flatso

https://github.com/Mark-H/ClientConfig/issues/111

**Comment by jcamachott** [comment]
Hi Wayne, it was a mod_security issue
